# yaml-language-server: $schema=../schemas/sentinel.schema.json
polling:
  github:
    interval_seconds: 60
    scope:
      repos:
        - chequer-io/querypie-frontend
        - chequer-io/querypie-backend
      filter_reasons:
        - review_requested
        - assign
        - mention
        - comment
        - state_change
  jira:
    interval_seconds: 300
    scope:
      jql_base: "project = QPD AND type in standardIssueTypes() AND 스프린트 IN openSprints() AND assignee = currentUser()"
